version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: 
      - webhook.slack-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks: 
      - webhook.slack-network

  consumer:
    image: furstlevy/fiap_webhook_slack_worker:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      KafkaServer: "kafka:29092"
      KafkaTopic: "aoj69"
      SlackBaseUrl: "https://hooks.slack.com"
      SlackServiceUrl: "/services/TNXJWU7L0/BQAATG132/Vxw33doNqBHUT9UfS5KcWiBd"
    depends_on:
      - kafka
    networks: 
      - dotnet-kafka-network

networks: 
  webhook.slack-network:
    driver: bridge
